### ISSUE TITLE
[BUG] Illegal character (: in windows) used in the file name

### ISSUE THREAD

**Issue by DManavi** [mathematic-inc/ts-japi#11]
## Describe the bug

A colon is an invalid character for a Windows file name. You won't be able to allow ':' in the file name and you used it in the file `src/interfaces/json:api.interface.ts`.

## To Reproduce

Install this package as a dependency to a NodeJS project and run it.

## Expected behavior<sup>*</sup>

Rename the file and use either dash or underscore as a separator.

## Screenshots

![image](https://user-images.githubusercontent.com/10468359/88149055-ca14e280-cc14-11ea-8fb5-4e751ef1107b.png)

## Platform

- [X] OS: Windows - All versions
- [ ] Browser: No browser
- [X] Version: 1.2.6

**Comment by jrandolf** [comment]
I'll compile this in the next minor.

**Comment by DManavi** [comment]
Thanks. It would be great if you could publish it sooner.
I believe that this package is used in both production and development projects so patching this critical bug (since it prevents the application from starting) would be a good idea.

**Comment by jrandolf** [comment]
It's out :)
