### ISSUE TITLE
Incorrect URL associated with repo

### ISSUE THREAD

**Issue by themaxdavitt** [mathematic-inc/ts-japi#13]
The URL associated with this repo (next to the description) points to [`https://jun-sheaf.github.io/ts-japi/`](https://jun-sheaf.github.io/ts-japi/) but it should point to [`https://mu-io.github.io/ts-japi/`](https://mu-io.github.io/ts-japi/). Should be an easy fix, just wanted to let you know!

**Comment by jrandolf** [comment]
Fixed!
