### ISSUE TITLE
[BUG] Serializer doesn't work as expected with depth greater than 1

### ISSUE THREAD

**Issue by jaridmargolin** [mathematic-inc/ts-japi#23]
## Describe the bug<sup>*</sup>

Serializer doesn't include resources past first level of depth.

## To Reproduce<sup>*</sup>

**Code:**
```ts
describe("Serializer", () => {
  it("Should traverse a depth > 1", async () => {
    type A = { id: string; prop: string }
    type B = { id: string; prop: string }
    type C = { id: string; prop: string }

    const counters = { AtoB: 0, BtoC: 0 }

    const SerializerC = new Serializer<C>("c")

    const BtoCRelator = new Relator<B, C>(async (data) => {
      counters.BtoC++
      return { id: "1", prop: "c" }
    }, SerializerC)

    const SerializerB = new Serializer<B>("b", {
      relators: { c: BtoCRelator },
    })

    const AtoBRelator = new Relator<A, B>(async (data) => {
      counters.AtoB++
      return { id: "1", prop: "b" }
    }, SerializerB)

    const SerializerA = new Serializer<A>("a", {
      relators: { b: AtoBRelator },
    })

    const serialized = await SerializerA.serialize(
      { id: "1", prop: "a" },
      { depth: 2 }
    )

    console.log(
      `A to B: ${counters.AtoB}\nB to C: ${
        counters.BtoC
      }\nSerialized Data:\n${inspect(serialized, false, 20)}`
    )
    counters.AtoB = counters.BtoC = 0
  })
})
```

**Output:**
```
  console.log
    A to B Fetch Count: 3
    B to C Fetch Count: 2
    Serialized Data:
    {
      jsonapi: { version: '1.0' },
      data: Resource {
        type: 'a',
        id: '1',
        attributes: { prop: 'a' },
        relationships: {
          b: Relationship { data: ResourceIdentifier { type: 'b', id: '1' } }
        }
      },
      included: [
        Resource {
          type: 'b',
          id: '1',
          attributes: { prop: 'b' },
          relationships: {
            c: Relationship {
              data: ResourceIdentifier { type: 'c', id: '1' }
            }
          }
        }
      ]
    }
```

## Expected behavior<sup>*</sup>

Referencing the example above, I would expect that resource C would be included. What I find interesting, is that the fetch method of the relator IS being called (actually multiple times which I may report as an additional bug).

Am I misunderstanding how depth is intended to work? I attempted to search through the tests, but I didn't see an example that was using a depth > 1.

**Comment by jaridmargolin** [comment]
# Update

I've been attempting to work through `recurseRelators` util, and I believe I can confirm that this is in fact a bug and not a misunderstanding.

Looking at https://github.com/mu-io/ts-japi/blob/master/src/utils/serializer.utils.ts#L33, this clause will never evaluate to true as the `newData` array is never populated.

I may be wrong, but I think `newData` should be removed, and the intended behavior is to use `relatedData`. Doing so results in the following output from my test above:

```
  console.log
    A to B Fetch Count: 3
    B to C Fetch Count: 3
    Serialized Data:
    {
      jsonapi: { version: '1.0' },
      data: Resource {
        type: 'a',
        id: '1',
        attributes: { prop: 'a' },
        relationships: {
          b: Relationship { data: ResourceIdentifier { type: 'b', id: '1' } }
        }
      },
      included: [
        Resource {
          type: 'b',
          id: '1',
          attributes: { prop: 'b' },
          relationships: {
            c: Relationship {
              data: ResourceIdentifier { type: 'c', id: '1' }
            }
          }
        },
        Resource { type: 'c', id: '1', attributes: { prop: 'c' } }
      ]
    }
```

Which corrects the output, but I would still like to investigate if there is a code path to reduce the amount of times the `fetch` method of the Relator is called.

**Comment by jrandolf** [comment]
Thanks for the issue. I reviewed the code and noticed the oddities. A fix for the critical issue will be published in a few hours.

As for the multiple calls, this may be from the Relationships, but considering we aren't actively using this library, I'm afraid we won't fix this anytime soon. Of course, PRs are always welcome.
