### ISSUE TITLE
[Bug] Stray console log in release 1.5.1

### ISSUE THREAD

**Issue by tomlagier** [mathematic-inc/ts-japi#28]
## Describe the bug<sup>*</sup>

In release 1.5.1, there is a console log in the `recurseRelators` function on NPM:

```
function recurseRelators(data, relators, depth, keys) {
    return __awaiter(this, void 0, void 0, function () {
        var included, queue, _a, data_1, relators_1, _loop_1, i, len;
        var _this = this;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0:
                    included = [];
                    queue = [[data, Object.values(relators)]];
                    console.log(data); << **Here**
                    _b.label = 1;
```                   

## To Reproduce<sup>*</sup>

1. Create serializer
2. Add relators
3. Run `serializer.serialize(data)`
4. Observe data is console log

## Expected behavior<sup>*</sup>

No stray console logs

Re-publishing the repo from source should remove the console log, it's not checked in. I'd suggest publishing releases as tags on git as well to make it easier to track the state of the code at previous versions.

**Comment by jrandolf** [comment]
It will be removed in the next release which should be around today.
